
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# To auto create table
#spring.jpa.hibernate.ddl-auto=create
# Enabling H2 Console
spring.h2.console.enabled=true
# Custom H2 Console URL
spring.h2.console.path=/h2

spring.application.name=CUSTOMER-DETAIL
server.port=9090
spring.config.import=optional:configserver:
#CUSTOMER-PAYMENT.ribbon.eureka.enabled= false
#CUSTOMER-PAYMENT.ribbon.listOfServers= localhost:9091/payment
# To make sure after creating table application will start
spring.jpa.defer-datasource-initialization=true
spring.h2.console.settings.web-allow-others=true

eureka.client.service-url.default-zone=http://localhost:8761/eureka

spring.zipkin.base-url=http://localhost:9411/

resilience4j.retry.instances.customer-detail.maxAttempts=5
#resilience4j.retry.instances.customer-detail.maxRetryAttempts=5
resilience4j.retry.instances.customer-detail.waitDuration=1s
resilience4j.retry.instances.customer-detail.enableExponentialBackoff=true