
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# To auto create table
#spring.jpa.hibernate.ddl-auto=create
# Enabling H2 Console
spring.h2.console.enabled=true
# Custom H2 Console URL
spring.h2.console.path=/h2

spring.config.import=optional:configserver:

#Kafka properties
spring.kafka.producer.bootstrap-servers= localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer= org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.topic= customer_details_topic
#spring.kafka.producer.properties.spring.json.trusted.packages=com.customer.details.model

#CUSTOMER-PAYMENT.ribbon.eureka.enabled= false
#CUSTOMER-PAYMENT.ribbon.listOfServers= localhost:9091/payment
# To make sure after creating table application will start
spring.jpa.defer-datasource-initialization=true
spring.h2.console.settings.web-allow-others=true

spring.zipkin.base-url=http://localhost:9411/

resilience4j.retry.instances.customer-detail.maxAttempts=5
#resilience4j.retry.instances.customer-detail.maxRetryAttempts=5
resilience4j.retry.instances.customer-detail.waitDuration=1s
resilience4j.retry.instances.customer-detail.enableExponentialBackoff=true